### PR TITLE
Add resource method to LitFormModel

### PR DESCRIPTION
**Pull request by albertpratomo**
Related to issue #97: Add `fieldsToArray` method to `LitFormModel`.

I need some help. I want to create a unit test for the `fieldsToArray` method.

The idea is to create an `Ignite\Crud\Models\Form` instance, fill it with some fields and value, then make a snapshot of the return value of `fieldsToArray`.

However, I'm not sure what is the easiest way to fill the form with fields? I can't find a similar test that has this setup or something in `TestSupport` that can help this.

Originally I'd like to unit test the `LitFormModel` class itself, but it's an abstract class so might be even harder to instantiate and fill with fields.

Some suggestion will be appreciated. 😄

### CODE REVIEW

**Comment by cbl** [comment]
Hey @albertpratomo,

I created the CrudResource class which renders the LitFormModel like did in the `fieldsToArray` method. This allows you to use the return the resource e.g in a controller like this:

```php
return $form->resource();
```

Also I added the methods `only` and `except` which allows you to prevent certain fields from being rendered:

```php
return $form->resource()->only('foo');
return $form->resource()->except('foo');
```

The `only` and `except` method accepts an array as well as multiple arguments:

```php
return $form->resource()->only('foo');
return $form->resource()->only('foo', 'bar');
return $form->resource()->only(['foo', 'bar']);
```

To answer your question about the tests. Unfortunately there are no direct unit tests for the **LitFormModel** yet. However, some integration tests cover most of it. I started to build a test environment with the required classes for the model. You can see an example in CrudResourceTest:

```php
    /** @test */
    public function it_renders_field_data()
    {
        $model = new DummyLitFormModel([
            'config_type' => Fixtures\ConfigWithTwoInputFormFields::class,
        ]);
        $model->save();
        $model->update(['foo' => 'fooo', 'bar' => 'barr']);

        $this->assertEquals(
            ['id' => $model->id, 'foo' => 'fooo', 'bar' => 'barr'],
            $model->resource()->toArray(request())
        );
    }
```

**Comment by albertpratomo** [comment]
Hi @cbl 

Thanks for improving the PR and adding the block field test.

I'd like to introduce snapshot testing, which I found really helpful to assert arrays. The idea is on first test run, a snapshot file will be generated, the developer has to check that the snapshot is correct. Then, for the subsequent runs, the snapshot will be used as the "master key" / source of truth.

I think the benefits are:
1. It is very clear in the snapshot, what is the "correct" result that is expected. This can act as a mini documentation.
2. Less code and easier to write the test. Developer doesn't have to write down what is the expected value.

My company uses this extensively to test the responses of our `GET` API endpoints, I think it will be beneficial for Litstack as well..

**Comment by cbl** [comment]
Hey @albertpratomo, 

I appreciate the effort, however I prefer to not add more dependencies to litstack at the moment. Snapshot testing is a nice thing, however in this case the Array is small and you don't need to open the file to see the expected array.

Please revert the last 2 commits, then I will merge the pr.

Thanks in any case for the new feature!

**Comment by albertpratomo** [comment]
@cbl Ah I see.. Yeah the argument about dependency is understandable. I will revert them 👍

**Comment by cbl** [comment]
Thanks! 🚀

**Comment by jannescb** [comment]
👏

**Pull request merged**
