### PR TITLE
Refactor HasMedia trait

### LINKED ISSUE #111: keepOriginalImageFormat for LitMediaForm's medias
Would be nice if `Ignite\Crud\Models\Traits\HasMedia` calls `keepOriginalImageFormat()` during `registerMediaConversions()`. At the moment my JPG images are being converted to PNG for the conversions.

Also I think `Ignite\Crud\Models\Concerns\HasMedia` is not needed because `Traits\HasMedia` has been used by `LitFormModel`.

I can make a PR for this if you guys agree with this proposal. 😃

### PR DESCRIPTION
**Pull request by albertpratomo**
Fix #111

- Call `keepOriginalImageFormat()` during media conversion
- Remove redundant `Crud\Models\Traits\HasMedia` trait
- Enable user to `setConversionsKey()` to use other conversions than `default`

### CODE REVIEW

**Comment by cbl** [comment]
Hey @albertpratomo, thanks for this. We Just need to move the `HasMedia` trait to `Crud\Models\Traits\HasMedia`. Otherwise it would be a breaking Change since this trait might be used by others Models

**Comment by albertpratomo** [comment]
Ok, I will delete `Crud\Models\Concerns\HasMedia` then?

**Comment by cbl** [comment]
Yes move `Crud\Models\Concerns\HasMedia` to `Crud\Models\Traits\HasMedia`

**Comment by cbl** [comment]
Thanks for the work @albertpratomo!

**Pull request merged**
