### PR TITLE
fix overflow on login page

### PR DESCRIPTION
**Pull request by nikolai-nikolajevic**

### CODE REVIEW

**Comment by cbl** [comment]
Hey @nikolai-nikolajevic please provide screenshots that show what you are fixing.

**Comment by nikolai-nikolajevic** [comment]
litstack-overflow

there is a tiny horizontal overflow

after:
litstack-overflow-fix

**Review by jannescb — APPROVED** [review]
👍

**Comment by cbl** [comment]
Thanks @nikolai-nikolajevic !

**Pull request merged**
