### PR TITLE
Multiple Crud Forms

### PR DESCRIPTION
**Pull request by cbl**
This pr adds support for multiple forms within one Crud.

There will be a route for every method that gets the `Ignite\Curd\CrudShow` class as the first parameter. The method name will be the slug. Except for the show method, this is reached directly without slug.

The routes for the following example would be:

- `admin/posts` Showing the page configured in `Page::index`.
- `admin/posts/1` Showing the page configured in `Page::show`.
- `admin/posts/1/foo` Showing the page configured in `Page::foo`.

```php
class PostConfig extends CrudConfig
{
    public function routePrefix()
    {
        return "posts";
    }

    public function index(CrudIndex $page)
    {
        //
    }

    public function show(CrudShow $page)
    {
        //
    }

   public function foo(CrudShow $page)
    {
        //
    }
}
```

## Redirect To The Correct Form From Index Table

You may want to redirect the user, when clicking on the index table item, to a certain form depending on the model. This can be achived by specifying returning this form in the `getFormNameFor` method in your crud config:

The following example would redirect the user to the `foo` form, whenever the type attribute equals `foo`, otherwise the default form is used:

```php
/**
 * Get the form name for the given Model.
 *
 * @param  Model  $model
 * @return string
 */
public function getFormNameFor($model)
{
    if ($model->type == 'foo') {
        return 'foo';
    }

    return 'show';
}
```

## Create/Update Only

You may now use a form for updating or creating only.

Whenever the method requires the `Ignite\Crud\CrudShow` class there will be a route to both the update and create view. However when the classes `Ignite\Crud\CrudCreate` or `Ignite\Crud\CrudUpdate` are type hinted. Only the associated routes will be present.

### Create Only

```php
use Ignite\Crud\CrudCreate;

public function show(CrudCreate $page)
{
    //
}
```

### Update Only

```php
use Ignite\Crud\CrudUpdate;

public function show(CrudUpdate $page)
{
    //
}
```

### CODE REVIEW

**Comment by kostopravby** [comment]
I don't understand how to use "create only" form.
I give error 
TypeError
Argument 1 passed to Lit\Config\Crud\AllvoucherConfig::show() must be an instance of Ignite\Crud\CrudCreate, instance of Ignite\Crud\CrudShow given, called in /var/www/html/vendor/litstack/litstack/src/Config/ConfigFactory.php on line 53

My code:

<?php

namespace Lit\Config\Crud;
```

use App\Models\Vouchers;
use Ignite\Crud\Config\CrudConfig;
use Ignite\Crud\CrudIndex;
use Ignite\Crud\CrudShow;
use Lit\Http\Controllers\Crud\AllvoucherController;
use Ignite\Crud\CrudCreate;
...................
public function show(CrudCreate $page)
    {
        $page->group(function ($page) {
            $page->card(function ($form) {
                $form->input('voucher_code')->width(1 / 2);
            });
        });            
    }
```

**Comment by cbl** [comment]
@kostopravby This should fix it: https://github.com/litstack/litstack/commit/8996d4ea22df4c6624dfd69ba0d711ccf459348b

**Comment by kostopravby** [comment]
Now get error:
Argument 2 passed to Ignite\Crud\Config\Factories\CrudFormConfigFactory::bindEventsFromConfig() must be an instance of Ignite\Crud\CrudShow, instance of Ignite\Crud\CrudCreate given, called in /var/www/html/vendor/litstack/litstack/src/Crud/Config/Factories/CrudFormConfigFactory.php on line 82

Ignite\Crud\Config\Factories\CrudFormConfigFactory::bindEventsFromConfig
vendor/litstack/litstack/src/Crud/Config/Factories/CrudFormConfigFactory.php:117
```
/**

     * Bind events from config.

     *

     * @param  ConfigHandler $config

     * @param  CrudShow      $page

     * @return void

     */

    protected function bindEventsFromConfig(ConfigHandler $config, CrudShow $page)

    {
```

**Comment by cbl** [comment]
@kostopravby Seem's like you are misunderstanding something. This is ment for Crud only not for Forms. Forms cannot be created, only updated.

**Comment by kostopravby** [comment]
I thought that I could create one form for update model and another for create. or just one only for creating

**Comment by cbl** [comment]
Okay, that may be a bit of an inaccurate description. By a `form` is meant a **page** for a model on which several fields are. So like in the example the Post Crud has two forms (pages) 1. show, 2. foxo

**Comment by kostopravby** [comment]
So no any chances to split create and update form. For example I want on update form make all fields read only (just display some additional fields that missed in table) and make create form with editable fields.

**Pull request merged**
